### ISSUE TITLE
Implement resampling?

### ISSUE THREAD

**Issue by doko-desuka** [tmarrinan/cube2equirect#2]
I noticed that the image result has a lot of jagged lines (aliasing).
Have you considered implementing a resampling function? (bicubic, lanczos etc.)

**Comment by tmarrinan** [comment]
Just pushed bilinear interpolation. This program uses OpenGL shaders to perform the conversion. OpenGL textures can automatically resample using bilinear interpolation, but not bicubic. Hopefully this helps!
